services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./instance:/app/instance
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-default-secret-key}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///instance/guitar.db}
      - FLASK_ENV=${FLASK_ENV:-production}
    env_file:
      - .env
    restart: always 